//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace REPORTES
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pagos
    {
        public int Id { get; set; }
        public int PrestamoId { get; set; }
        public Nullable<decimal> MontoAnterior { get; set; }
        public Nullable<decimal> InteresPagado { get; set; }
        public Nullable<decimal> MontoAbonado { get; set; }
        public Nullable<decimal> NuevoMonto { get; set; }
        public Nullable<System.DateTime> FechaPago { get; set; }
    
        public virtual Prestamos Prestamos { get; set; }
    }
}
